version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_FRONT_URL=http://localhost:5173

  api:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/app"
      - /app/node_modules
      - ./backend/data:/app/data
    environment:
      - DATABASE_PATH=/app/data/database.sqlite
      - VITE_FRONT_URL=http://localhost:5173
